### ISSUE TITLE
Is slack_cleaner2 available as a Docker image?

### ISSUE THREAD

**Issue by donbeave** [sgratzl/slack_cleaner2#26]
Sorry, probably a stupid question. 

Originally I have used this version: `docker run -it --rm sgratzl/slack-cleaner`, now are looking to migrate to the second version, but on Docker Hub can not find it: https://hub.docker.com/u/sgratzl/

Is the new version are not available on Docker Hub yet?

**Comment by sgratzl** [comment]
no there is none. slack_cleaner2 is designed as a library while slack_cleaner is designed as a CLI. 

However, you can simple create an own image based on https://hub.docker.com/_/python/ and running `pip install slack_cleaner2`

**Comment by jpwynn** [comment]
A little more detail would be so helpful re how to run python scripts that use slack_cleaner2 inside docker container that is interactively running the right version of python.

A simple `pip install slack_cleaner2` on a brand new Mac, for example warns about not using python 2.7. Upgrading python system-wide may be ill-advised since 2.7 is pre-installed for various legacy purposes. 

So helpful would be instructions how to:
* have the SC2 scripts inside a folder `sc_stuff`, such as mytask1.py, mytask2.py
* run an interactive shell inside docker with the correct version of python and with slack_cleaner2 installed
* be able to run `python mytask1.py` in the inside-docker shell

It is doubtless pretty simple... unless one happens to be both docker and python novice for whom the original slack_cleaner was nicely setup.

(The shortcoming in the original slack_cleaner that I'm hopoing to find the v2 handles is v1 did not seem to clean up threads within a channel or group)

**Comment by sgratzl** [comment]
> (The shortcoming in the original slack_cleaner that I'm hopoing to find the v2 handles is v1 did not seem to clean up threads within a channel or group)

even when using a release after https://github.com/sgratzl/slack-cleaner/releases/tag/v0.7.1

re docker file: https://github.com/sgratzl/slack_cleaner2/tree/develop#docker
