### ISSUE TITLE
is there a way to delete 1:1 DM by creating & using some sort of MEMBER-SPECIFIC token?

### ISSUE THREAD

**Issue by jpwynn** [sgratzl/slack_cleaner2#39]
> readme says: You can only delete your own messages, not the ones of others. This is due to a restriction in the Slack API and there is nothing one can do about it.

If our members are A, B, C I understand that the normal admin token used for deleting channel messages wont work for 1:1 DMs.

But if we dont mind having user-specific versions of Slackcleaner, is it possible to create some kind of  "token A" on Slack that WOULD permit SlackCleaner delete DMs from member A, and _another_ token for member B, etc?

Or is that what the readme is saying is that Slack literally offers zero _API_ method for user A to delete their own DMs?

**Comment by sgratzl** [comment]
yes, each token owner can delete his/her own direct messages. I used a similar a approach in which I collected a token from each user and then run a clean operation for each user individually. This will also allow you to clean all private channels, since any token owner can only see the private channels he/she is a member of.

**Comment by jpwynn** [comment]
Thank you Samuel!

Can you point the way to whereever a member of my slack space would "create or get" whatever token they need to give me? (Sounds like one must log in AS that user to get/create that user's correct token, the admin cannot get it on their own?)

**Comment by sgratzl** [comment]
haven't done that in a while but each user just needs to follow: https://github.com/sgratzl/slack_cleaner2#token.
